### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by bkamuz** [GeorgGrebenyuk/Renga_python_shell#1]
**Версия:** 6.0.50429.0 64-разрядная

![image](https://github.com/GeorgGrebenyuk/Renga_python_shell/assets/118307284/de69c2fa-b699-40b9-b399-9fc44a608218)

Подскажи, где найти журнал? Или возможно уже известно как решить эту проблему?

**Comment by GeorgGrebenyuk** [comment]
> Подскажи, где найти журнал?

Вообще, журнал лежит по такому пути `%localappdata%\Renga Software\Renga\AecApp.log`
А так ... всё что угодно может быть, логгирование "почему не удается" у программы отвратительное. Кроме того, мне бы надо в этом проекте пометить, что он не развивается уже. Я попробовал, посмотрел на сложности и бросил, там много надо копаться, но методология "очерчена".
